import { StyleSheet } from 'react-native';

// Define Colors object
const Colors = {
  aliceBlue: '#F0F8FF',
  white: 'hsl(186, 72%, 24%)',
  grayWeb: '#808080',
  verdigris: '#40E0D0',
  gainsboro: '#DCDCDC',
  black: '#000000',
  midnightGreen: '#004953',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'hsl(182, 100%, 35%)',
    borderWidth: 1,
    borderColor: 'hsl(186, 72%, 24%)',
    borderRadius: 10,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: 'hsl(186, 72%, 24%)',
    marginBottom: 40,
  },
  inputContainer: {
    width: '80%',
    marginBottom: 20,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'hsl(186, 72%, 24%)',
    borderRadius: 10,
    padding: 10,
  },
  input: {
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: 'hsl(186, 72%, 24%)',
    paddingVertical: 10,
    fontSize: 16,
    color: 'hsl(186, 72%, 24%)',
  },
  inputIcon: {
    position: 'absolute',
    right: 0,
    top: 10,
    color: 'hsl(186, 72%, 24%)',
  },
  button: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'hsl(186, 72%, 24%)',
    borderRadius: 25,
    padding: 15,
    width: '80%',
    alignItems: 'center',
    marginTop: 20,
  },
  buttonText: {
    color: 'grey',
    fontWeight: 'bold',
    fontSize: 16,
  },
  rememberContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: 'hsl(186, 72%, 24%)',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxInner: {
    width: 12,
    height: 12,
    backgroundColor: 'hsl(186, 72%, 24%)',
  },
  rememberText: {
    color: 'grey',
  },
  forgotButton: {
    marginTop: 20,
    borderWidth: 1,
    borderColor: 'hsl(186, 72%, 24%)',
    borderRadius: 25,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  forgotText: {
    color: 'hsl(186, 72%, 24%)',
  },
  joinButton: {
    marginTop: 30,
    borderWidth: 1,
    borderColor: 'hsl(186, 72%, 24%)',
    borderRadius: 25,
    paddingVertical: 10,
    paddingHorizontal: 30,
  },
  joinText: {
    color: 'hsl(186, 100%, 19%)',
    fontWeight: 'bold',
    fontSize: 16,
  },
  dashboardContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'hsl(186, 72%, 24%)',
    borderRadius: 10,
  },
  scrollView: {
    flex: 1,
  },
  appBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: Colors.white,
  },
  appBarTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  greetingContainer: {
    padding: 16,
    backgroundColor: Colors.white,
  },
  greeting: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.midnightGreen,
  },
  subGreeting: {
    fontSize: 14,
    color: Colors.grayWeb,
    marginTop: 4,
  },
  sectionContainer: {
    marginTop: 24,
    padding: 16,
    backgroundColor: Colors.white,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.midnightGreen,
    marginBottom: 16,
  },
  conditionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  conditionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.aliceBlue,
    borderRadius: 8,
    padding: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  conditionText: {
    marginLeft: 8,
    color: Colors.midnightGreen,
  },
  medicalRecordsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  medicalRecordItem: {
    width: '48%',
    backgroundColor: Colors.white,
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  medicalRecordImage: {
    width: '100%',
    height: 100,
    resizeMode: 'cover',
    borderRadius: 8,
  },
  medicalRecordTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 8,
    color: Colors.midnightGreen,
  },
  medicalRecordDate: {
    fontSize: 12,
    color: Colors.grayWeb,
    marginTop: 4,
  },
  viewButton: {
    backgroundColor: Colors.verdigris,
    borderRadius: 4,
    padding: 8,
    marginTop: 8,
    alignItems: 'center',
  },
  viewButtonText: {
    color: Colors.white,
    fontWeight: 'bold',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navbar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: Colors.white,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.gainsboro,
  },
  navItem: {
    alignItems: 'center',
  },
});

// Main screen